import Head from "next/head";
import Image from "next/image";
import { createContext, useState } from "react";
import LogoStripAnimated from "../components/molecules/LogoStripAnimated";
import HeaderArea from "../components/organism/HeaderArea";
import NavBar from "../components/organism/NavBar";
import PopUpNav from "../components/organism/PopUpNav";
import useMediaQuery from "@mui/material/useMediaQuery";
import FullyIntegrated from "../components/organism/FullyIntegrated";
import Footer from "../components/organism/Footer";
// import styles from "../styles/Home.module.css";
import { Poppins } from "@next/font/google";
import BuiltInMinutes from "../components/organism/BuiltInMinutes";
import PavelonAPIs from "../components/organism/ImageBoxAndList";
import GetStarted from "../components/organism/GetStarted";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import TabSwitchTest from "../components/molecules/TabSwitchTest";

const theme = createTheme({
  status: {
    danger: "#e53e3e",
  },
  palette: {
    primary: {
      main: "#0971f1",
      darker: "#053e85",
    },
    neutral: {
      main: "#fff",
      contrastText: "#fff",
    },
  },
});

const poppins = Poppins({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const IndexContext = createContext<null | object>(null);

const subNavItems = [
  ["KYC", "Identity API"],
  ["BAAS", "Investment As A Service", "Insurance As A Service"],
  ["Credify", "Credify Mall"],
  [
    "Digital Lending API",
    "Capital By API",
    "KYC/Onboarding API",
    "Digital Accounts API",
  ],
];

export default function Home() {
  const [showSubNav, setShowSubNav] = useState(false);
  const [subNavContentIndex, setSubNavContentIndex] = useState(0);
  const [subNavTitle, setSubNavTitle] = useState("");
  const matches = useMediaQuery("(max-width:600px)");

  return (
    <div>
      <Head>
        <title>Pavelon v2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TabSwitchTest />
      <ThemeProvider theme={theme}>
        <IndexContext.Provider
          value={{
            setShowSubNav,
            setSubNavContentIndex,
            matches,
            subNavTitle,
            setSubNavTitle,
          }}
        >
          <NavBar showSubNav={showSubNav} setShowSubNav={setShowSubNav} />
          {showSubNav && (
            <PopUpNav menuToDisplay={subNavItems[subNavContentIndex]} />
          )}
          <HeaderArea setShowSubNav={setShowSubNav} />
          <LogoStripAnimated
            headertitle={"Powering Business, small and LARGE"}
            imageUrls={[
              "/logostrip/creditmall.png",
              "/logostrip/credify.png",
              "/logostrip/stanbic.f6f4ec42.png",
              "/logostrip/yango.f54ab341.png",
              "/logostrip/gcb_logo.cb4c2a8d.png",
            ]}
          />
          <FullyIntegrated />
          <BuiltInMinutes />
          <PavelonAPIs
            flexCol={true}
            listItems={[
              {
                title: "Enhanced KYC & Digital Accounts",
                description:
                  "See how Pavelon can help you build, embed or enhance your credit products so you can acquire more customers, increase revenue and accelerate growth.",
              },
              {
                title: "Digital Lending & Capital By API",
                description:
                  "See how Pavelon can help you build, embed or enhance your credit products so you can acquire more customers, increase revenue and accelerate growth.",
              },
              {
                title: "Card Issuance & Disbursement API",
                description:
                  "See how Pavelon can help you build, embed or enhance your credit products so you can acquire more customers, increase revenue and accelerate growth.",
              },
              {
                title: "Financial Data & Embedded Commerce",
                description:
                  "See how Pavelon can help you build, embed or enhance your credit products so you can acquire more customers, increase revenue and accelerate growth.",
              },
            ]}
            image={"/pavelonApis/paveApi.png"}
          />
          <GetStarted />

          {/* <PavelonAPIs /> */}
          <Footer />
        </IndexContext.Provider>
      </ThemeProvider>
    </div>
  );
}
