import Head from "next/head";
import Image from "next/image";
import { createContext, useState } from "react";
import LogoStripAnimated from "../components/molecules/LogoStripAnimated";
import HeaderArea from "../components/organism/HeaderArea";
import NavBar from "../components/organism/NavBar";
import SubNav from "../components/organism/SubNav";
// import styles from "../styles/Home.module.css";

export const IndexContext = createContext<null | object>(null);
const subNavItems = [
  ["KYC", "Idenity API"],
  ["BAAS", "Investment As A Service", "Insurance As A Service"],
  ["Credify", "Credify Mall"],
];

export default function Home() {
  const [showSubNav, setShowSubNav] = useState(false);
  const [subNavContentIndex, setSubNavContentIndex] = useState(0);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IndexContext.Provider value={{ setShowSubNav, setSubNavContentIndex }}>
        <NavBar showSubNav={showSubNav} setShowSubNav={setShowSubNav} />
        {showSubNav && (
          <SubNav menuToDisplay={subNavItems[subNavContentIndex]} />
        )}
        <HeaderArea setShowSubNav={setShowSubNav} />
        {/* set currentClickIndex from menu index */}
      </IndexContext.Provider>
      <LogoStripAnimated
        headertitle={"Powering Business, small and LARGE"}
        imageUrls={[
          "/logostrip/credify.png",
          "/logostrip/creditmall.png",
          "/logostrip/credify.png",
          "/logostrip/credify.png",
        ]}
      />
    </div>
  );
}
