import Head from "next/head";
import LogoStripAnimated from "../components/molecules/LogoStripAnimated";
import HeaderArea from "../components/organism/HeaderAreaLargerImages";
import FullyIntegrated from "../components/organism/FullyIntegrated";
import BuiltInMinutes from "../components/organism/BuiltInMinutes";
import PavelonAPIs from "../components/organism/ImageBoxAndList";
import GetStarted from "../components/organism/GetStarted";
import { useMediaQuery } from "@mui/material";

export default function Home({ setShowSubNav }) {
  const matches = useMediaQuery("(max-width:600px)"); //Check viewport isk mobilefirst

  return (
    <div>
      <Head>
        <title>Pavelon v2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <TabSwitchTest /> */}

      {/* <HeaderArea setShowSubNav={setShowSubNav} /> */}
      <HeaderArea title="Lending Infrastructure for Africa.">
        {" "}
        <p className="text-xl" style={{ width: `${matches ? "80vw" : ""}` }}>
          Technology and infrastructure to launch and scale your fintech in
          Africa.
        </p>
        <p className="text-xl" style={{ width: `${matches ? "85vw" : ""}` }}>
          Use Pavelon’s APIs to embed a full range of credit services on your
          platform to increase revenue streams.
        </p>
      </HeaderArea>
      <LogoStripAnimated
        headertitle={"Powering Business, small and LARGE"}
        imageUrls={[
          "/logostrip/creditmall.png",
          "/logostrip/credify.png",
          "/logostrip/stanbic.f6f4ec42.png",
          "/logostrip/yango.f54ab341.png",
          "/logostrip/gcb_logo.cb4c2a8d.png",
        ]}
      />
      <FullyIntegrated />
      <BuiltInMinutes />
      <PavelonAPIs
        flexCol={true}
        listItems={[
          {
            title: "Enhanced KYC & Digital Accounts",
            description:
              "See how Pavelon can help you build, embed or enhance your credit products so you can acquire more customers, increase revenue and accelerate growth.",
          },
          {
            title: "Digital Lending & Capital By API",
            description:
              "See how Pavelon can help you build, embed or enhance your credit products so you can acquire more customers, increase revenue and accelerate growth.",
          },
          {
            title: "Card Issuance & Disbursement API",
            description:
              "See how Pavelon can help you build, embed or enhance your credit products so you can acquire more customers, increase revenue and accelerate growth.",
          },
          {
            title: "Financial Data & Embedded Commerce",
            description:
              "See how Pavelon can help you build, embed or enhance your credit products so you can acquire more customers, increase revenue and accelerate growth.",
          },
        ]}
        image={"/pavelonApis/paveApi.png"}
      />
      <GetStarted />

      {/* <PavelonAPIs /> */}
    </div>
  );
}
